### PR TITLE
Pull in ni/priv changes into ni/current

### PR DESCRIPTION
**Pull request by pvallone**
**What this PR does / why we need it**:
Rebase ni/priv onto ni/current (just like Cameron did [here](https://github.com/ni/grafana/pull/11)).

**Which issue(s) this PR fixes**:

N/A

**Special notes for your reviewer**:
Pulling in latest set of changes to ni/current.

### CODE REVIEW

**Review by mure — APPROVED** [review]

**Review by cameronwaterman — APPROVED** [review]

**Comment by cameronwaterman** [comment]
uhoh

_"Rebasing the commits of this branch on top of the base branch cannot be performed automatically as this would create a different result than a regular merge."_

**Comment by pvallone** [comment]
@cameronwaterman the trick is to press the blue highlighted button when completing this PR, right? Ideally this belongs in CONTRIBUTING.MD but I've got too much on my plate right now.

image

**Comment by pvallone** [comment]
> uhoh
> 
> _"Rebasing the commits of this branch on top of the base branch cannot be performed automatically as this would create a different result than a regular merge."_

Where do you see that? There was a merge conflict that I needed to resolve, so maybe it went away after I fixed that?

**Comment by cameronwaterman** [comment]
> > uhoh
> > _"Rebasing the commits of this branch on top of the base branch cannot be performed automatically as this would create a different result than a regular merge."_
> 
> Where do you see that? There was a merge conflict that I needed to resolve, so maybe it went away after I fixed that?

image

**Comment by cameronwaterman** [comment]
> @cameronwaterman the trick is to press the blue highlighted button when completing this PR, right? Ideally this belongs in CONTRIBUTING.MD but I've got too much on my plate right now.
> 
> image

Yeah that is what I did.

**Comment by pvallone** [comment]
> > > uhoh
> > > _"Rebasing the commits of this branch on top of the base branch cannot be performed automatically as this would create a different result than a regular merge."_
> > 
> > 
> > Where do you see that? There was a merge conflict that I needed to resolve, so maybe it went away after I fixed that?
> 
> image

Oh, gotcha. This reminds me that the OpenSSL policy was to *merge* changes into ni/current, not to rebase, so perhaps this is why. We should probably just start merging, then. I didn't have a good reason to strongly prefer rebasing anyway.

**Review by kjohn1922 — APPROVED** [review]

**Pull request merged**
