### PR TITLE
Rebase ni/priv on ni/current

### PR DESCRIPTION
**Pull request by cameronwaterman**
**What this PR does / why we need it**:

Rebase ni/priv onto ni/current.

**Which issue(s) this PR fixes**:

N/A

**Special notes for your reviewer**:

Pulling in latest set of changes to ni/current.

### CODE REVIEW

**Comment by cameronwaterman** [comment]
Hmm I thought there was an option in the GitHub UI to change the merge to a rebase?

Edit: Ah, it shows up after approval.

**Review by pvallone — APPROVED** [review]

**Comment by pvallone** [comment]
> Hmm I thought there was an option in the GitHub UI to change the merge to a rebase?

Hmm, not sure.. I usually do all my git magic in the sublime merge GUI.

**Review by kjohn1922 — APPROVED** [review]

**Comment by cameronwaterman** [comment]
Almost deleted the ni/priv branch... eek! @mure - I thought this shouldn't be possible?

**Comment by pvallone** [comment]
> Almost deleted the ni/priv branch... eek! @mure - I thought this shouldn't be possible?

Fortunately we won’t have to do this rebase manually any more once we get the github workflow working.

**Pull request merged**
