### PR TITLE
Add minimal helm chart with admin/test login

### PR DESCRIPTION
**Pull request by pvallone**
**What this PR does / why we need it**:

Just adding a minimal helm chart skeleton. A follow-up PR will modify `azure-pipelines.yml` to package and publish the chart.

**Which issue(s) this PR fixes**:

https://ni.visualstudio.com/DevCentral/_workitems/edit/1799084

**Special notes for your reviewer**:

Adding temporary hardcoded login credentials is technically in another story, but I wanted to put something in the `values.yml` now, and not having predefined credentials was going to make testing a pain anyways. Note that I was going to use a username/password combination that is more common at NI, but we're in a public github repo and I didn't want those internal credentials in the commit history.

Testing steps:
`cd helm`
`helm install nigrafana .`
`kubectl get-pods`
*copy/paste the name of the grafana pod*
`kubectl port-forward pod_name_here 3000:3000`
*Login via admin/test at localhost:3000 in my browser*

### CODE REVIEW

**Comment by cameronwaterman** [comment]
Should we add a policy to require code owner approval to merge in this branch?

**Review by cameronwaterman — APPROVED** [review]

**Comment by pvallone** [comment]
> Should we add a policy to require code owner approval to merge in this branch?

Yeah, that sounds reasonable. I'll set that up. How do we feel about these settings?
image
image


It probably makes sense to make ni/current the default branch too? I don't know if that'll break your GitHub bot @mure

**Comment by cameronwaterman** [comment]
Looks good to me - and yeah, it sounds reasonable to make it the default as well. Not sure the implications of doing so though.

**Comment by mure** [comment]
@pvallone I'm planning to turn off the bot given the new branching strategy. I may try to set up an action or webhook to create PRs on new tagged releases instead.

**Comment by pvallone** [comment]
- Default branch is now ni/current
- Added the screenshotted branch policy (still happy to iterate on it)

**Comment by pvallone** [comment]
I set the default branch back to `main`. I started seeing some github workflow error emails as soon as I switched it, and I'm hoping this will make the errors go away until we can investigate what else we need to change.

**Comment by mure** [comment]
I had manually disabled all the GitHub actions in this repo after forking. I'm not sure if changing the default branch reset that. Either way, it looks like ni/current is still the default branch, and I disabled the workflows again for the time being.

**Comment by pvallone** [comment]
@mure yeah sorry I meant to send another update - I set the branch back to ni/current after it didn't have an effect on the spam. That's good to know that we're intending for the workflows to be disabled for now.

**Comment by pvallone** [comment]
Abandoning this PR, as the working plan is to source the helm chart and its pipeline in AzDO.

**Pull request closed without merging**
